- name: Install nfs
  apt:
    name: nfs-common
    state: present
  become: yes
- name: Install openmpi
  apt:
    name: openmpi-bin
    state: present
  become: yes
- name: Install gcc
  apt:
    name: gcc
    state: present
  become: yes
- name: Install libomp-dev
  apt:
    name: libomp-dev
    state: present
  become: yes
- name: Install htop
  apt:
    name: htop
    state: present
  become: yes
- name: Mount nfs share
  mount:
    path: /home/nick/cloud
    src:  192.168.122.248 :/home/nick/cloud
    fstype: nfs
    #opts: defaults,nobootwait
    state: mounted
  become: yes
